### ISSUE TITLE
Invalid target location for CommandsMixin fabric class

### ISSUE THREAD

**Issue by Shylie** [jakobkmar/level-border#1]
According to [the fabric wiki](https://fabricmc.net/wiki/tutorial:mixin_injects#injecting_into_constructors), only `TAIL` or `RETURN` are valid injections for constructors

https://github.com/jakobkmar/level-border/blob/46e5d779420aed367802844451cbb05ce37041a0/level-border-fabric/src/main/java/net/axay/levelborder/fabric/mixin/CommandsMixin.java#L22

**Comment by jakobkmar** [comment]
Have a look at [this line here](https://github.com/FabricMC/fabric/blob/1.18/fabric-command-api-v1/src/main/java/net/fabricmc/fabric/mixin/command/CommandManagerMixin.java#L45) to see how the fabric-api itself registers commands.
It is definitely a valid Mixin, tested and works. The wiki just mentions that it is not guaranteed that targets other than TAIL or RETURN work.

**Comment by Shylie** [comment]
I couldn't get it to work on my end, actually.

**Comment by jakobkmar** [comment]
Probably, in which environment have been trying to get it working?

**Comment by Shylie** [comment]
Fabric.

**Comment by jakobkmar** [comment]
Could you please share the error message?

**Comment by jakobkmar** [comment]
That's just a warning, not an error.
