### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by janinator12478** [jakobkmar/level-border#3]
I want to play it on my server so i downloaded the fabric version for 1.18.1 from 2021-12-17 and put it into the plugins folder in the Spigot server folder. Then i started the world but it's just a normal world with the normal border. When i type /plugins it also sais, there are 0 plugins.
I also tried it the same way with a timer plugin and it worked really well.
Later i tried it with some other extra software and it worked, but i had to use the minecraft launcher and singleplayer, i'd like to play it using badlion client and on my server.
So, is there a way to play it on my server and with the badlien client instead of minecraft launcher?

**Comment by jakobkmar** [comment]
Which jar did you download?

**Comment by janinator12478** [comment]
I downloaded "Level Border [Fabric] 1.1.0" so the
"level-border-fabric-1.1.0.jar".

Jakob K ***@***.***> schrieb am So., 19. Dez. 2021, 19:57:

**Comment by jakobkmar** [comment]
> I downloaded "Level Border [Fabric] 1.1.0" so the
"level-border-fabric-1.1.0.jar".

as it says there, this is for fabric, not for anything else

you can also download any of the other three available versions for other platforms

**Comment by janinator12478** [comment]
I already thought this is why it doesn't work, but how can i make it run on
a spigot server?

Jakob K ***@***.***> schrieb am So., 19. Dez. 2021, 20:43:

**Comment by jakobkmar** [comment]
If you want to be in the spigot ecosystem and use leve-border, you have to use Paper.
