### ISSUE TITLE
Wrong border center in nether

### ISSUE THREAD

**Issue by CrazySaft** [jakobkmar/level-border#4]
if i set the worldborder with 7setworldspawn it works just fine in the overworld except in the nether there it works after several restarts and plugin reloads again only with / setworldspawn BUT i keep getting damaged like if I would be outside the border but i can break blocks and see the border.

Would be really nice i you could fix that that would make my day because its such a good idea this plugin.

**Comment by Janoiboy** [comment]
bei mir auch. bin in den nether gegangen und war tot hab alles verloren

**Comment by jakobkmar** [comment]
Die falsche Position der Border im Nether sollte mit dem nächsten Release gefixt sein.

Should be fixed with the next release.

**Comment by CrazySaft** [comment]
Thanks very much you are a Hero finally i can use the nether lol

**Comment by 456634** [comment]
Ist mit der 1.2.0 fabric leider nicht behoben. Das Portal hat sich bei 54/31/-22 aufgebaut bei level 26. Die visuelle border geht vermutlich von 0.0 aus. Das Portal liegt somit außerhalb. Man kann dort nichts abbauen, bekommt jedoch keinen Schaden. Geht man in die Border, kann man abbauen. Geht man ungefähr richtung 0.0 bekommt man jedoch Schaden. Hier scheinen sich die visuelle/abbau Border von der Schadensborder zu unterscheiden.

Hoffe du kannst das Fixen. Danke für die Arbeit.

**Comment by CrazySaft** [comment]
Befor die neue version rauskam ging bei mir der nether nicht wie oben beschrieben dann nach dem fix wurde bei mir der port aber an nem komplett neuen ort aufgebaut als vorher nämlich genau dort wo es ein muss overworld coords÷8 aber vorher war es  bei mir ohne neues release ca. 300blöcke weiter weg also ist bei mir auf meinem paper server wurde das portal irgendwie korrekt aufgebaut ich vermute mal das liegt am plguin damit alles funktioniert denn ich habe den nether unzälige male resettet aber. Port immer am selben ort erst nach neuer version "korrekte" position 
Also demnach kann ich bestätigen in paper funktionierts perfekt 
Btw. Ich habe den port ca. 15 blocks vom weltspawnpunkt entfert (nicht 0 0) 

Danke noch jakobmar für deine Hilfe und anpassung des Plugins
